### ISSUE TITLE
Parsing lambda expression with variables does not work

### ISSUE THREAD

**Issue by kikogatto** [TrigerSoft/jaque#5] opened 2015-05-22 13:49 UTC
Hi,
I am trying to use Jaque to parse a SerializablePredicate<T> in order to build a MongoDB query.

It works fine like this:
LambdaExpression<SerializablePredicate<Person>> ex = LambdaExpression.parse(t -> t.getName() == "Maria Bonita");

Or even like this:
    public void testExpression2() {
        this.testExpression(t -> t.getName() == "Maria Bonita");
    }
    protected void testExpression(SerializablePredicate<Person> p) {
        final LambdaExpression<SerializablePredicate<Person>> ex = LambdaExpression.parse(p);
        assertNotNull(ex);
    }

But if I try to use name as a String variable, it will not work AND try to parse from the file system, throwing a misleading exception;

Attached is a JUnit test file that will show what I mean. Just run the tests.
Ops, turns out I cant attach .java files. The code is bellow:
__________________________________

/**
 *
 */
package commons.queries;

import static org.junit.Assert.assertNotNull;

import java.io.Serializable;
import java.util.function.Predicate;

import org.junit.Test;

import com.trigersoft.jaque.expression.LambdaExpression;

/**
 * @author gatto
 */
public class SerializablePredicateTest {

    @Test
    public void testExpression1() {
        final LambdaExpression<SerializablePredicate<Person>> ex = LambdaExpression.parse(t -> t.getName() == "Maria Bonita");
        assertNotNull(ex);
    }

    @Test
    public void testExpression2() {
        this.testExpression(t -> t.getName() == "Maria Bonita");
    }

    @Test
    public void testExpression3() {
        final String name = "Maria Bonita";
        this.testExpression(name);
    }

    @Test
    public void testExpression4() {
        this.testExpression("Maria Bonita");
    }

    protected void testExpression(final String name) {
        this.testExpression(t -> t.getName() == name);
    }

    protected void testExpression(SerializablePredicate<Person> p) {
        final LambdaExpression<SerializablePredicate<Person>> ex = LambdaExpression.parse(p);
        assertNotNull(ex);
    }
}

interface SerializablePredicate<T> extends Predicate<T>, Serializable {

}

class Person {
    private String name;

    /**
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }
}

**Comment by kostat** [comment] 2015-05-22 19:58
The tests above were added to the suite and all passed. Please see the commit above for details. Hence closing the issue. Please add more information if the problem still exists.

**Closed by kostat** 2015-05-22 19:58 UTC

**Comment by kikogatto** [comment] 2015-05-22 21:05
Hey,
thanks for the quick answer.
They will only work with the jdk.internal.lambda.dumpProxyClasses property set.
The tests will not pass without the configuration bellow, even if the lambdas are Serializable.

				<configuration>
					<systemPropertyVariables>
<jdk.internal.lambda.dumpProxyClasses>${HOME}/lambda</jdk.internal.lambda.dumpProxyClasses>
					</systemPropertyVariables>
				</configuration>

It is meant to work without the property if the lambda is Serializable, right?

**Comment by kostat** [comment] 2015-05-22 22:22
The issue is fixed with side note that the wrapping LambdaExpression misses the captured arguments. Since the Body is correct and only it's important for tree analysis, I consider the issue minor. A separate issue #6 is created.

**Comment by kikogatto** [comment] 2015-05-22 23:21
Hey,
My usecase is building a query for MongoDB based on a Predicate.
Something like :

    User user = userRepository.findByUsername(username); // username is a String received as argument

    User findByUsername(String username) {
        LambdaExpression<SerializablePredicate<User>> ex = LambdaExpression.parse(t -> t.getUsername() == username);
        Bson query = ex.accept(bsonVisitor)
        return this.collection.find(bson).first();
    }

Therefore I need to be able to parse a SerializablePredicate with variable arguments.

Can you point me towards the solution? I will be happy to try and fix it.

**Comment by kostat** [comment] 2015-05-23 05:31
Jaque is needed when the query is not known at design time, i.e. if you know that the query is user.getUsername() == username, code that directly with mongoDB tools! So your sample is not clear...

In any case with my latest commit I fixed the issue with SerializedPredicate and you can parse it and analyze its expression tree without dumpProxyClasses property set.

**Comment by kostat** [comment] 2015-05-23 14:45
With the #6 fix all works correctly now.
